# Generated by Django 3.1.7 on 2021-03-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210316_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_default_address',
            new_name='default_street_address',
        ),
    ]
