# Generated by Django 3.1.7 on 2021-03-16 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0003_auto_20210315_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='user_profile_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='profiles.userprofileinfo'),
        ),
    ]
