# Generated by Django 3.1.7 on 2021-03-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_receipt_user_profile_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='user_profile_info',
            new_name='user_profile',
        ),
    ]
